### ISSUE TITLE
Use interfaces

### ISSUE THREAD

**Issue by benkeil** [codechips/svelte-and-typescript#1]
I have a file `Foo.ts`

```
export default interface Foo {
  name: string;
}
```

and want to include it into `App.svelte`

```
import Foo from './Foo';
const foo: Foo = {
  name: 'foo',
};
```

and get an error:

```
[!] Error: 'default' is not exported by src/Foo.ts, imported by src/App.svelte
```

**Comment by codeitlikemiley** [comment]
think this is cause by rollup plugin typescript....

i tried to use parcel 
https://github.com/goldcoders/svelte-tsc

it works , @codechips  any reason this is not working on your set up?
misconfigured? 

i hate compile time of parcel but the no config saves me headache for this stuffs...
sad tradeoff , ill try to test this on svite ...

if that work then i can move out of parcel

**Comment by goldcoders** [comment]
@benkeil you should use

```
export interface Foo {
  name: string;
};
```

then on your App.svelte

```
import type {Foo} from './foo'

const foo: Foo = {
  name: 'bar'
}

console.log(foo.name)
```
The reason behind is the compiler automatically stripped TYPE (Interfaces that is imported) so it throws an error,

on typescript documentation it is sited there that you need to use  import type...

**Comment by codechips** [comment]
Exactly. I've read somewhere (don't remember now) that exporting interfaces does not work very well.

Maybe this one? https://github.com/pyoner/svelte-typescript/issues/23

**Comment by goldcoders** [comment]
been studying typescript together with rust  this lockdown for months, all this static analysis is killing me lol
but its worth investment since the technology is going towards web assembly , wasm , rust, typescript.

I have actually preparing myself for building a hugo site manager with rust , svelte and typescript...
so finding the best Bundler to speed up development is a must..

@codechips  can you sugguest your best set up? :)

**Comment by codechips** [comment]
Hmm .. Hugo like in static site generator written in Go? If going down that route parcel is probably the best because it only needs one entry file in your main html file. However, I do not recommend you to use parcel as it produces large and not that optimal production bundles compared to Rollup. 

I would probably use pure Vitejs myself here with its Svelte plugin. Vitejs supports HMR, PostCSS, TS and other nice things, plus it uses Rollup for production bundles. Currently it also uses esbuild for Typescript, but see here https://github.com/vitejs/vite/issues/788

As of Rust and WASM, I have no knowledge here except that Vite can import precompiled WASM files.

Snowpack is also an option, but I would personally stay away from it for now.
